name: language-ocaml
version: 0.1.0.0
github: "HS-Flensburg-PLTP/language-ocaml"
license: BSD-3-Clause
author: "Jan Christiansen"
maintainer: "jan.christiansen@hs-flensburg.de"
copyright: "2024 Jan Christiansen"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/ocaml#readme>

dependencies:
  - base >= 4.7 && < 5
  - megaparsec
  - path
  - shelly
  - text

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    Language.OCaml.AST
    Language.OCaml.Parser
  other-modules: []

executables:
  language-ocaml-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - language-ocaml

tests:
  language-ocaml-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - language-ocaml
